### ISSUE TITLE
DBusException at /login/

### ISSUE THREAD

**Issue by aderusha** [Royrdan/anycubic_cloud#2]
Allright, you closed the issue I raised by moving that file over, thanks man!  It still seems to be in the wrong place so now the instructions need to add a step to copy it to the place where the code expects it to be:  `cp ~/anycubic_cloud/src/anycubic_cloud/api_endpoints.yaml ~/anycubic_cloud/src`

Once I do that, I get a new error in the login process:

    DBusException at /login/
    org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

Have you had a chance to deploy this code to a new system?  I think it'd help you out a lot to see what a new user is going through, there are a lot of assumptions about dependencies etc in this project and I suspect that nobody is going to be able to run this outside of your dev system.  Try throwing up a clean VM, deploy your code, and see what happens.

Here's what I have for the install process currently on a clean Ubuntu 20.04 LTS host:

```bash
cd ~
sudo apt install -y git python3 python3-dev python3-virtualenv python-dbus libdbus-1-dev libglib2.0-dev
virtualenv anycubic_cloud
cd ~/anycubic_cloud
source bin/activate
python3 -m pip install --upgrade pip
pip3 install django django-crispy-forms requests pyyaml notify2 dbus-python
mkdir src
cd src
git clone https://github.com/Royrdan/anycubic_cloud
mv anycubic_cloud anycubic_cloud_repo
cp ~/anycubic_cloud/src/anycubic_cloud/api_endpoints.yaml ~/anycubic_cloud/src
django-admin startproject anycubic_cloud

SECRET_KEY=$(grep -h "SECRET_KEY" anycubic_cloud/anycubic_cloud/settings.py | sed 's/.* = //')
cp -r anycubic_cloud_repo/* anycubic_cloud 
sed -i "s/SECRET_KEY = <SECRET_KEY_HERE>/# SECRET_KEY = <see bottom of file>/" anycubic_cloud/anycubic_cloud/settings.py
echo "SECRET_KEY = $SECRET_KEY" >> anycubic_cloud/anycubic_cloud/settings.py

~/anycubic_cloud/src/anycubic_cloud/manage.py migrate
~/anycubic_cloud/src/anycubic_cloud/manage.py runserver
```

**Comment by Royrdan** [comment]
Awsome.
Thanks so much for sending all this through @aderusha. The installation instructions are so much better!
I have been able to recreate the venv and install the system as per the instructions on the updated readme and thanks for your updated commands to simplify the process.
I have also removed the notify2 app as this seems depreciated and was causing issues with different systems. I have moved to desktop-notifier which should hopefully work better cross platform.
I probably rushed the release process but was keen to get this out and knew there were going to be issues. I do want to release this as a django app eventually but just waiting to find the time.
Thanks again for your help. Let me know how you go with the new instructions and config
